eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    
microservice:
	customer:
		endpoints:
			endpoint:
				uri: http://customer/api/v1/customers
	fraud:
		endpoints:
			endpoint:
				uri: http://fraud/fraudapi/v1/fraud-check
